# Generated by Django 5.0.2 on 2024-03-05 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(default='Пользователь', max_length=50, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_settings', models.BooleanField(default=True, verbose_name='Настройка уведомлений')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'Пользователи',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Идея',
                'verbose_name_plural': 'Идеи на будущее',
                'db_table': 'Идеи',
            },
        ),
        migrations.CreateModel(
            name='Pdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdp_title', models.CharField(max_length=100, verbose_name='Карьерная цель')),
                ('smart', models.CharField(blank=True, max_length=700, null=True, verbose_name='Карьерная цель по SMART')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdps', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'ИПР',
                'verbose_name_plural': 'ИПР',
                'db_table': 'ИПР',
            },
        ),
        migrations.CreateModel(
            name='Personal_goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_goal_title', models.CharField(max_length=300, verbose_name='Личная цель')),
                ('personal_goal_smart', models.CharField(blank=True, max_length=700, null=True, verbose_name='Личная цель по SMART')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_goal', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Личная цель',
                'verbose_name_plural': 'Личные цели',
                'db_table': 'Личные цели',
            },
        ),
        migrations.CreateModel(
            name='Personal_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_activity', models.CharField(max_length=200, verbose_name='Действие')),
                ('regular_one_time', models.CharField(blank=True, choices=[('regular', 'Регулярное действие'), ('one time', 'Разовое действие')], null=True, verbose_name='Регулярное / разовое')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('done', models.BooleanField(default=False, verbose_name='Статус')),
                ('personal_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_activities', to='gtapp.personal_goal', verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'db_table': 'Действия',
                'ordering': ('expected_date',),
            },
        ),
        migrations.CreateModel(
            name='Сompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=200, verbose_name='Компетенция')),
                ('current_level', models.CharField(blank=True, choices=[('Не владею', 'Не владею'), ('Есть представление', 'Есть представление'), ('Есть небольшой опыт', 'Есть небольшой опыт'), ('Немного владею', 'Немного владею'), ('Неплохо владею', 'Неплохо владею'), ('Полностью владею', 'Полностью владею')], null=True, verbose_name='Уровень владения')),
                ('theory', models.CharField(blank=True, max_length=200, null=True, verbose_name='Обучение')),
                ('theory_exp_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('theory_done', models.BooleanField(default=False, verbose_name='Статус')),
                ('practice', models.CharField(blank=True, max_length=200, null=True, verbose_name='Практика')),
                ('practice_exp_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('practice_done', models.BooleanField(default=False, verbose_name='Статус')),
                ('pdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сompetencies', to='gtapp.pdp', verbose_name='ИПР')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
                'db_table': 'Компетенции',
            },
        ),
    ]
