# Generated by Django 5.0.2 on 2024-02-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Пользователь', max_length=50, verbose_name='Имя'),
        ),
    ]
