# Generated by Django 5.0.2 on 2024-03-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='сompetence',
            name='practice_done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='сompetence',
            name='theory_done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
