# Generated by Django 5.0.2 on 2024-02-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_pdp',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='financial_activity',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='financial_goal',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pdp',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='personal_activity',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='personal_goal',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
