# Generated by Django 5.0.2 on 2024-02-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ideas',
            new_name='Idea',
        ),
    ]
