# Generated by Django 5.0.2 on 2024-03-02 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0003_alter_financial_activity_finance_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_activity',
            name='finance_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_activities', to='gtapp.financial_goal', verbose_name='Финансвоая цель'),
        ),
        migrations.AlterField(
            model_name='financial_goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goal', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pdp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdps', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='personal_activity',
            name='personal_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_activities', to='gtapp.personal_goal', verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='personal_goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_goal', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='сompetence',
            name='pdp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сompetencies', to='gtapp.pdp', verbose_name='ИПР'),
        ),
    ]
