# Generated by Django 5.0.2 on 2024-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtapp', '0004_alter_financial_activity_finance_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сompetence',
            name='current_level',
            field=models.CharField(blank=True, choices=[('Не владею', 'Не владею'), ('Есть представление', 'Есть представление'), ('Есть небольшой опыт', 'Есть небольшой опыт'), ('Немного владею', 'Немного владею'), ('Неплохо владею', 'Неплохо владею'), ('Полностью владею', 'Полностью владею')], null=True, verbose_name='Уровень владения'),
        ),
    ]
